Removed default menus, added new font to menu, got rid of main menu u…
vppatel111/HITDAD pull request #119
Opened 2020-03-23 03:03 UTC by ConnorSheremeta

…nneeded content, removed saves

2020-03-23 15:36 UTC, vppatel111 commented on HITDAD/js/rpg_windows.js
> +    fthis.initialize.apply(this, arguments);
Was this intentional or is this a typo?

2020-03-23 15:44 UTC, vppatel111 commented
A couple more issues:

- It appears that the pressing the "Esc" key now does nothing. This is a problem because you can't back out of "Continue" menu or pause during a game.
- Additionally, you removed the "Options" option from the menu but we still want to allow the player to change the game volume from the title screen, we only wanted to remove the TMJumpAction configuration, please see here: https://sevenpointsoffailure.slack.com/archives/CSDFVG2UA/p1584633475047700

Note: You can remove menu options from the ingame menu from Database > System > Menu Commands. You only need to change the code for TMJumpAction to remove their menu item, the others can be done through the interface.

2020-03-23 15:45 UTC, vppatel111 requested changes
See above comments.

2020-03-26 21:48 UTC, ConnorSheremeta commented
Menus now removed properly, removed typo, esc now works, all options now on options selection again other than jap option

2020-04-01 16:52 UTC, mikegreber approved these changes
Looks good, i merged my map-updates in here and did a fix on a bug that showed up with the level names not displaying properly. For some reason the menu font doesn't load in when the game is initially loaded but we can figure that out later.

2020-04-01 16:53 UTC, merged